
spring:
  profiles:
    include: jms-embedded

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:gatling;MODE=MSSQLServer
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
    close-timeout: 15000
    non-blocking-redelivery: false
    password: admin
    user: admin
    send-timeout: 0
    packages:
      trust-all: false
      trusted: com.memorynotfound
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      create-connection-on-startup: true
      enabled: false
      expiry-timeout: 0
      idle-timeout: 30000
      max-connections: 1
      maximum-active-session-per-connection: 500
      reconnect-on-exception: true
      time-between-expiration-check: -1
      use-anonymous-producers: true
  
  jms: 
    jndi-name:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template: 
      default-destination: empty
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000  

hibernate:
  dialect: org.hibernate.dialect.H2Dialect

amq:
  broker-uri: ${spring.activemq.broker-url}
  user: ${spring.activemq.user}
  password: ${spring.activemq.password}
  
logging.root.dir: target/
